### ISSUE TITLE
Missing assets on ahab.io

### ISSUE THREAD

**Issue by devarispbrown** [ahabio/ahab.io#45]
When I navigate to ahab.io the assets are missing.

Console Output: http://www.screencast.com/t/4VjJH4RhjvtH

Page View: http://www.screencast.com/t/GjuJKoSh

**Comment by jamesarosen** [comment]
The first problem was that the CDN was still pointing to the old IP (before the move to Heroku). I fixed that. Then the problem is that the CDN passes through the _original_ request host (`assets.ahab.io`), which Heroku didn't know about. I ran `heroku domains:add assets.ahab.io`, which cleared things up.
